import React from 'react';
import SEO from '../src/components/SEO';
import SiteFooter from '../src/components/SiteFooter';

export default function Staticabout() {
  return (
    <>
  <SEO title="About Cointist" description="About Cointist — independent crypto news, research, and explainers focused on clarity and data." url="/about" canonical={(process.env.SITE_URL || 'https://cointist.net') + '/about'} />
      {/* Topbar & Header are rendered globally in pages/_app.js; only render main content here */}
      <div dangerouslySetInnerHTML={{ __html: "<main class=\"page-wrap\"><div class=\"container page\" style=\"max-width:1100px;margin:0 auto;padding:24px 18px;font-family:'SF Pro Text','SF Pro Display',system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;line-height:1.6;color:#e9f2ed;\">\n<section style=\"margin:10px 0 28px;text-align:center;\">\n<h1 style=\"font-family:'SF Pro Display',sans-serif;font-size:2.2rem;font-weight:650;letter-spacing:.2px;margin:6px 0 14px;\n             background:linear-gradient(90deg,#fbfffe 0%,#b7ffe3 55%,#69fe3c 100%);-webkit-background-clip:text;background-clip:text;color:transparent;text-align:center;\">\n    About Cointist\n  </h1>\n<p style=\"max-width:820px;margin:0 auto 10px auto;text-align:center;\">Cointist delivers sharp crypto news, research, and explainers with a bias for clarity. We pair rigorous reporting with clean design and data‑forward visuals to help readers make sense of markets fast.</p>\n<p style=\"max-width:820px;margin:0 auto 10px auto;text-align:center;\">Our editorial standards emphasize accuracy, transparency, and source attribution. We avoid hype, disclose conflicts, and correct mistakes promptly.</p>\n</section>\n<section style=\"display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px;margin:18px 0 24px;\">\n<div style=\"border:1px solid #26332d;border-radius:16px;padding:22px 18px;background:linear-gradient(135deg,#2ce561 0%,#e6fcf7 100%);box-shadow:0 1px 0 #1b231f;color:#0E0E0F;display:flex;flex-direction:column;align-items:center;text-align:center;\">\n<h3 style=\"margin:0 0 10px;font-weight:650;font-size:1.18rem;\">What we cover</h3>\n<p style=\"margin:0 0 2px;font-size:1.04rem;max-width:90%;\">Bitcoin &amp; macro • Ethereum &amp; L2s • DeFi • Security • Regulation • On‑chain data • How‑tos.</p>\n</div>\n<div style=\"border:1px solid #26332d;border-radius:16px;padding:22px 18px;background:linear-gradient(135deg,#2ce561 0%,#e6fcf7 100%);box-shadow:0 1px 0 #1b231f;color:#0E0E0F;display:flex;flex-direction:column;align-items:center;text-align:center;\">\n<h3 style=\"margin:0 0 10px;font-weight:650;font-size:1.18rem;\">How we work</h3>\n<p style=\"margin:0 0 2px;font-size:1.04rem;max-width:90%;\">Editorial independence, clear disclosures, primary‑source verification, and timely corrections.</p>\n</div>\n<div style=\"border:1px solid #26332d;border-radius:16px;padding:22px 18px;background:linear-gradient(135deg,#2ce561 0%,#e6fcf7 100%);box-shadow:0 1px 0 #1b231f;color:#0E0E0F;display:flex;flex-direction:column;align-items:center;text-align:center;\">\n<h3 style=\"margin:0 0 10px;font-weight:650;font-size:1.18rem;\">Pitch us</h3>\n<p style=\"margin:0 0 2px;font-size:1.04rem;max-width:90%;\">Have a tip or a story idea? Email the newsroom at <a href=\"mailto:tips@cointist.com\" style=\"color:#050605; font-weight:800; font-size: large;\">tips@cointist.com</a>.</p>\n</div>\n</section>\n</div></main>" }} />
      <SiteFooter />
    </>
  );
}
