import React from 'react';
import SEO from '../src/components/SEO';
import SiteFooter from '../src/components/SiteFooter';

export default function Staticprivacy() {
  return (
    <>
  <SEO title="Privacy Policy" description="Cointist privacy policy — how we collect and use data, your choices, and contact details." url="/privacy" canonical={(process.env.SITE_URL || 'https://cointist.net') + '/privacy'} />
      {/* Topbar & Header are rendered globally in pages/_app.js; only render main content here */}
      <div dangerouslySetInnerHTML={{ __html: "<main class=\"page-wrap\"><div class=\"container page\" style=\"max-width:1100px;margin:0 auto;padding:24px 18px;font-family:'SF Pro Text','SF Pro Display',system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;line-height:1.6;color:#e9f2ed;\">\n<section style=\"margin:10px 0 18px;\">\n<h1 style=\"font-family:'SF Pro Display',sans-serif;font-size:2.2rem;font-weight:650;letter-spacing:.2px;margin:6px 0 14px;\n             background:linear-gradient(90deg,#fbfffe 0%,#b7ffe3 55%,#69fe3c 100%);-webkit-background-clip:text;background-clip:text;color:transparent;\">\n    Privacy Policy\n  </h1>\n<p style=\"max-width:820px;margin:0 0 6px;\">Effective date: August 15, 2025</p>\n<p style=\"max-width:820px;margin:0 0 10px;\">This policy explains what we collect, why we collect it, and how you can control your information across Cointist’s products and sites.</p>\n</section>\n<section style=\"max-width:860px;\">\n<h2 style=\"font-size:1.25rem;margin:0 0 6px;\">Information we collect</h2>\n<ul style=\"margin:0 0 12px 18px;\">\n<li>Account &amp; contact info (if you subscribe or contact us).</li>\n<li>Usage analytics (page views, device info, approximate location).</li>\n<li>Cookies for preferences, performance, and limited advertising measurement.</li>\n</ul>\n<h2 style=\"font-size:1.25rem;margin:14px 0 6px;\">How we use information</h2>\n<ul style=\"margin:0 0 12px 18px;\">\n<li>Provide and improve our services and content.</li>\n<li>Communicate with you about updates, newsletters, and promotions (with opt‑out).</li>\n<li>Detect fraud, abuse, and security incidents.</li>\n</ul>\n<h2 style=\"font-size:1.25rem;margin:14px 0 6px;\">Your choices</h2>\n<ul style=\"margin:0 0 12px 18px;\">\n<li>Opt‑out of non‑essential cookies via your browser or our banner controls.</li>\n<li>Unsubscribe from emails using the link in any message.</li>\n<li>Request access, correction, or deletion: <a href=\"mailto:privacy@cointist.com\" style=\"color:#69fe3c;\">privacy@cointist.com</a>.</li>\n</ul>\n<h2 style=\"font-size:1.25rem;margin:14px 0 6px;\">Data retention</h2>\n<p>We retain data only as long as necessary for the purposes outlined above or as required by law.</p>\n<h2 style=\"font-size:1.25rem;margin:14px 0 6px;\">Third‑party services</h2>\n<p>We may use analytics and embedded content providers that set their own cookies. Their use is governed by their policies.</p>\n<h2 style=\"font-size:1.25rem;margin:14px 0 6px;\">Updates</h2>\n<p>We’ll update this policy when practices change. Material changes will be highlighted on this page.</p>\n<h2 style=\"font-size:1.25rem;margin:14px 0 6px;\">Contact</h2>\n<p>Questions about privacy? Email <a href=\"mailto:privacy@cointist.com\" style=\"color:#69fe3c;\">privacy@cointist.com</a>.</p>\n</section>\n</div></main>" }} />
      <SiteFooter />
    </>
  );
}
