name: Generate BTC Weekly Report

on:
  schedule:
    - cron: '0 7 * * 0' # every Sunday at 07:00 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run generator
        run: node ./scripts/generate-btc-weekly.js

      - name: Commit generated report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/reports || true
          git commit -m "chore: generate btc weekly report [skip ci]" || echo "no changes"
          git push
