name: Generate sitemap-news

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Call sitemap generation endpoint
        id: call
        run: |
          set -euo pipefail
          echo "Calling sitemap generation endpoint (GET with query secret)..."
          # Build a safe base URL: accept either 'example.com' or 'https://example.com'
          if echo "$SITE_URL" | grep -qE '^https?://'; then
            base="$SITE_URL"
          else
            base="https://$SITE_URL"
          fi
          url="$base/api/generate-sitemap-news?secret=${SITEMAP_CRON_SECRET}"
          echo "Request URL: $url"
          # Use verbose curl for diagnostics, follow redirects and retry once
          resp=$(curl -v -s -S -L --retry 1 -w "\n%{http_code}" "$url") || true
          body=$(printf "%s" "$resp" | sed -n '1,$p' | sed '$d')
          code=$(printf "%s" "$resp" | tail -n1)
          echo "HTTP status: $code"
          echo "Response body: $body"
          if [ "$code" -lt 200 ] || [ "$code" -ge 300 ]; then
            echo "Sitemap generation failed with status $code"
            exit 1
          fi
        env:
          SITEMAP_CRON_SECRET: ${{ secrets.SITEMAP_CRON_SECRET }}
          SITE_URL: ${{ secrets.SITE_URL }}
